### ISSUE TITLE
在mac下编译报“无法找到字体”错误

### ISSUE THREAD

**Issue by mrbian** [megrxu/zju-report-latex-template#3]
## 问题
在mac下面运行`xelatex report.tex`，无法正常编译，错误提示为
```
! Package fontspec Error: The font "SimSun" cannot be found.
```

## 解决
后将zjureport.cls第27行（[传送门](https://github.com/megrxu/zju-report-latex-template/blob/master/zjureport.cls#L27)）
```
\setCJKmainfont[ItalicFont={KaiTi},BoldFont={SimHei}]{SimSun}
```
改为
```
\setCJKmainfont[ItalicFont={STKaiti},BoldFont={STHeiti}]{STSong}
```
即可正常编译。

## 分析
至于为什么，我也不太清楚(⊙﹏⊙)b。

**Comment by megrxu** [comment]
看起来是 Mac 下面的字体名称（宋体和楷体）名字和 Windows 上的不同？
不过问题解决了就 OK 啦。
其实 repo 里有带用到的几个字体，在 fonts 文件夹下，也可将该文件夹加入到字体搜索目录中。

**Comment by MySuperSoul** [comment]
Mac下的字体名称不一样，可以用fc-list :lang=zh查看可用的中文字体（刚刚解决的同样的问题
