### ISSUE TITLE
开头的栏目由于多个人名导致的重叠

### ISSUE THREAD

**Issue by beef-potato** [megrxu/zju-report-latex-template#4]
![1](https://user-images.githubusercontent.com/95594775/189647800-4b8e5b68-a7ac-47f3-adbc-436f348bebae.png)
如果有多个或者是比较长的人名需要填写，比如同组同学，虽然图片中的十分夸张，会造成重叠和溢出。
请问这样子要怎么处理?

**Comment by beef-patato** [comment]
> ![1](https://user-images.githubusercontent.com/95594775/189647800-4b8e5b68-a7ac-47f3-adbc-436f348bebae.png) 如果有多个或者是比较长的人名需要填写，比如同组同学，虽然图片中的十分夸张，会造成重叠和溢出。 请问这样子要怎么处理?
